name: exx-sr
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - pydantic
  - scipy
  - ipykernel
  - h5py
  - pip
  - sympy
  - scikit-learn
  - tqdm
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - symantic==1.1.0.6
